version: '3.4'

services:
  stagecheck_api:
    image: ${DOCKER_REGISTRY-}stagecheckapi
    build:
      context: .
      dockerfile: StageCheck_API/Dockerfile

  stagecheck_mvc_app:
    image: ${DOCKER_REGISTRY-}stagecheckmvcapp
    build:
      context: .
      dockerfile: StageCheck_MVC_app/Dockerfile

  stagecheck_web_app:
    image: stagecheck_web_app
    container_name: stagecheck_web_app
    build:
      context: .
      dockerfile: stagecheck_web_app/Dockerfile
    stdin_open: true
    ports:
      - 3010:3000
    volumes:
      - './stagecheck_web_app:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true